# Generated by Django 4.2.2 on 2023-06-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HasRouteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'has_route_source',
                'db_table_comment': 'keeps track of the Route-Source links, that is, which sources are supporting a route of interest. It saves the historical attestation of a route in a given source.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasWaypointSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'has_waypoint_source',
                'db_table_comment': 'keeps track of the Waypoint-Source links, that is, which sources are supporting a waypoint of interest. It saves the historical attestation of a route in a given source.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('historical', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'route',
                'db_table_comment': 'represents a route followed by pilgrims or salesmen to reach a specific destination (waypoint). Each route is made up at least of two waypoints and can be “historical” (i.e., based on historical evidence) or “conjectural” if it is just an hypothesis. Each route has a creator (i.e., a user which creates the route and saves it in the database for the first time) and a status indicating whether the route is just a draft or it has been confirmed by a user. Each route has a name and a description providing the user information about the route, so that it can be easily recognized. A route should have at least one type specified but can have multiple types (see the requirements section above) that are specified by means of the entity RouteType. ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_type',
                'db_table_comment': 'represents the type of a route, namely: Waterway, Postal route, Pilgrim road, Trade route ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_title', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('archive', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_series', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'source',
                'db_table_comment': 'it is an historical source of evidence supporting the existence of routes and waypoints. It can be primary or secondary (mutually exclusive) this information is specified by the attribute type. Note that, for this reason, some attributes concern only primary sources (i.e., TBD) whereas others refer to secondary ones (i.e., TBD). The attributes representing a source include (if applicable): title, short title, publication date, archive, series, sub-series, publisher, link, DOI, author. In addition, each source has a creator (i.e., a user which creates the source and saves it in the database for the first time) and a status indicating whether the source is just a draft or it has been confirmed by a user. ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('domainofexpertise', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('geonameref', models.CharField(blank=True, max_length=200, null=True)),
                ('whgref', models.CharField(blank=True, max_length=200, null=True)),
                ('miduraref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('spatial_geometry', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ascii_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('geonames_last_edit_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'waypoint',
                'db_table_comment': 'it is the “fundamental unit” of any route, indeed two waypoints can make up a route (see the minimum cardinality of hasWType relationship). Each waypoint has a creator (i.e., a user which creates the waypoint and saves it in the database for the first time) and a status indicating whether the waypoint is just a draft or it has been confirmed by a user. A description for each waypoint is provided helping the user realize the nature of the waypoint. In addition, geospatial information about the waypoint are saved (see MiduraRef, GeonameRef, WHGRef). Each waypoint should have at least one type specified but can have multiple types (see the requirements section above) that are specified by means of the entity WaypointType.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaypointType',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waypoint_type',
                'db_table_comment': 'represents the type of a waypoint, namely: Postal waystation, Postal terminus, City, Port, River port, Toll gate, University, Fair ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditRoute',
            fields=[
                ('route', models.OneToOneField(db_column='route', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maps.route')),
                ('timestamp', models.DateTimeField()),
                ('edited_attributes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edit_route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditSource',
            fields=[
                ('source', models.OneToOneField(db_column='source', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maps.source')),
                ('timestamp', models.DateTimeField()),
                ('edited_attributes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edit_source',
                'db_table_comment': 'keeps track of the updates and modifications of the attributes of a source, carried out by a user. It includes a timestamp of the update event as well as a JSON serialization of the key-value pairs related to the updated attributes.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditWaypoint',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maps.user')),
                ('timestamp', models.DateTimeField()),
                ('edited_attributes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edit_waypoint',
                'db_table_comment': 'keeps track of the updates and modifications of the attributes of a waypoint, carried out by a user. It includes a timestamp of the update event as well as a JSON serialization of the key-value pairs related to the updated attributes.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasRouteType',
            fields=[
                ('route', models.OneToOneField(db_column='route', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maps.route')),
                ('column_3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'has_route_type',
                'db_table_comment': 'indicates all the possible (multiple) different types of a given route.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasWaypoint',
            fields=[
                ('route', models.OneToOneField(db_column='route', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maps.route')),
                ('historical', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'has_waypoint',
                'db_table_comment': 'keeps track of the Route-Waypoint links, that is, which waypoints made up a route of interest. Moreover, It saves whether the waypoint is “historical” (i.e., based on historical evidence) or “conjectural” if it is just an hypothesis. ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasWaypointType',
            fields=[
                ('waypoint', models.OneToOneField(db_column='waypoint', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maps.waypoint')),
            ],
            options={
                'db_table': 'has_waypoint_type',
                'db_table_comment': 'indicates all the possible (multiple) different types of a given waypoint.',
                'managed': False,
            },
        ),
    ]
