# Generated by Django 4.2.2 on 2023-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
                'db_table_comment': 'Author information, such as author name and surname.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical', models.BooleanField(blank=True, db_column='historical', null=True)),
            ],
            options={
                'db_table': 'route_couple',
                'db_table_comment': 'indicates all the possible (multiple) different types of a given route.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaypointCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waypoint_couple',
                'db_table_comment': 'indicates all the possible (multiple) different types of a given waypoint.',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='haswaypointtype',
            name='waypoint',
        ),
        migrations.DeleteModel(
            name='HasRouteType',
        ),
        migrations.DeleteModel(
            name='HasWaypointType',
        ),
    ]
